# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: Stage1
    jobs:
      - job: UpdateChangeRequest
        steps:
          - task: UpdateServiceNowChangeRequest@2
            displayName: 'Update ServiceNow Change Request'
            inputs:
              ServiceNowConnection: 'SNConn'
              ChangeRequestNumber: 'CHG0030612'
              NewStatus: 'Implement'
              WorkNotes: 'Implementation Started'
              otherParameters: '{"u_close_notes": "succeeded" }'
          - task: UpdateServiceNowChangeRequest@2
            displayName: 'Update ServiceNow Change Request'
            inputs:
              ServiceNowConnection: 'SNConn'
              ChangeRequestNumber: 'CHG0030612'
              UpdateStatus: false
              WorkNotes: 'Release for creation of storage account'
          - task: UpdateServiceNowChangeRequest@2
            displayName: 'Close ServiceNow change [Successfull]'
            inputs:
              ServiceNowConnection: 'SNConn'
              ChangeRequestNumber: 'CHG0030612'
              NewStatus: 'Closed'
              WorkNotes: 'Completed all tasks for stage 1 in release'
              otherParameters: '{"u_status_reason":"successful", "u_work_start": "2021-12-07 02:00:00 UTC", "u_work_end": "2021-12-08 12:00:00 UTC", "u_close_code":"successful","u_close_notes":"Test closure notes"}'
pool: server